# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-08-25 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wenzhai', '0002_auto_20190825_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generation',
            name='AlreadyPrintNum',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='generation',
            name='Sign',
            field=models.CharField(max_length=50),
        ),
    ]
