# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-08-26 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wenzhai', '0003_auto_20190825_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='RemainPrintNum',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
